### ISSUE TITLE
Manually add 1.1.1-preview.5

### ISSUE THREAD

**Issue by rockwalrus** [needle-mirror/com.unity.package-manager-doctools#1]
Version `1.1.1-preview.5` is available on GitHub at https://github.com/Unity-Technologies/InputSystem/tree/develop/Packages/com.unity.package-manager-doctools .

**Comment by marwie** [comment]
I'd rather not add packages manually.

And adding it to our automated system is not as easy as with settings-manager package as this package is not available in the public packages registry at https://packages.unity.com/com.unity.package-manager-doctools or https://staging-packages.unity.com/com.unity.package-manager-doctools (at least we dont know the correct or complete url/headers)

Although the [documentation ](https://github.com/Unity-Technologies/InputSystem/blob/develop/Packages/com.unity.package-manager-doctools/Documentation~/index.md)says the registry is staging-packages.unity.com

**Comment by hybridherbst** [comment]
@rockwalrus I made an exception in this case and added the only public version 1.1.1-preview.5:
https://github.com/needle-mirror/com.unity.package-manager-doctools/releases/tag/1.1.1-preview.5

Note that Unity explicity states that this package is neither endorsed nor supported (and there's probably good reasons for it not being available through PackMan).
